---
title: "Graficacion"
author: "Nestor Veas"
format: html
toc: true
lang: es

---
#Carga de paquetes

```{r}
#| label: carga-paquetes
#| warning: false
#| message: false

library(tidyverse)
library(DT)
library(scales)
library(ggthemes)
library(hrbrthemes)
library(plotly)
```

# Carga de datos

```{r}
#| label: carga-datos
#| warning: false
#| message: false

paises <- read_csv("paises.csv")


```

```{r}

# Tabla de datos de paises
paises |> 
  select(NAME, CONTINENT, LIFE_EXPECTANCY, GDP_PC) |> 
  datatable(
  options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  )
)

```


# ggplot2

```{r}
#| label: grafico-01
#| warning: false
#| message: false

ggplot(data = paises) + 
  geom_point(mapping = aes(x = GDP_PC, y = LIFE_EXPECTANCY))

```

```{r}
#| label: grafico-02
#| warning: false
#| message: false
# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer


paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY))+
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))
  


```

```{r}
#| label: grafico-03
#| warning: false
#| message: false


# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con colores por continente



paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color=CONTINENT))+
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))

```

```{r}
#| label: grafico-04
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con formas por continente




paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, shape=CONTINENT))+
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))


```

```{r}
#| label: grafico-05
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con formas por continente



paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, shape=CONTINENT, color=CONTINENT))+
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))+
  scale_shape_manual(values= c(0,1,2,3,4,5,6,7))+
  scale_color_manual(values = c("black", "blue", "green", "purple", "orange", "brown", "pink", "yellow"))



```

```{r}
#| label: grafico-06
#| warning: false
#| message: false
# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con formas por continente




paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, size=POP_EST, shape=CONTINENT, color=CONTINENT))+
  geom_point() +
  scale_x_continuous(labels = comma, limits = c(0, NA))+
  scale_shape_manual(values= c(0,1,2,3,4,5,6,7))+
  scale_color_manual(values = c("black", "blue", "green", "purple", "orange", "brown", "pink", "yellow"))

```

```{r}
#| label: grafico-07
#| warning: false
#| message: false
 
# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con formas por continente

paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY))+
  geom_point() +
  geom_smooth(method ="lm")+
  scale_x_continuous(labels = comma, limits = c(0, NA))


```

```{r}
#| label: grafico-08
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con formas por continente


paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY))+
  geom_point() +
  geom_smooth(method ="loess")+
  scale_x_continuous(labels = comma, limits = c(0, NA))

```

## PANELES

```{r}
#| label: grafico-09
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per capita vs esperanza de vida al nacer con formas por continente
# paneles en función del continente




paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY))+
  geom_point() +
  facet_wrap(~ CONTINENT, nrow = 2)+
  scale_x_continuous(labels = comma, limits = c(0, NA))

```

```{r}
#| label: grafico-10
#| warning: false
#| message: false

# paneles en función de los ingresos y por continente

paises |> 
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY))+
  geom_point() +
  facet_grid(REGION_UN ~ INCOME_GRP)+
  scale_x_continuous(labels = comma, limits = c(0, NA))
```

## Títulos, etiquetas, estilos y colores

```{r}
#| label: grafico-11
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# en África y Europa coloreado por continente
# + curva de tendencia


paises |>
  filter(CONTINENT == 'Africa' | CONTINENT == 'Europe') |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color = CONTINENT)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_y_continuous(labels = comma, limits = c(50, 90)) +
  ggtitle("PIB per cápita vs esperanza de vida al nacer por continente") +
  xlab("PIB per cápita  (USD)") +
  ylab("Esperanza de vida (años)") +
  labs(subtitle = "Datos de África y Europa", 
       caption = "Fuentes: Natural Earth y Banco Mundial",
       color = "Continente")
```

## Estilos (*themes*)

```{r}
#| label: grafico-12
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# en África y Europa coloreado por continente
# + curva de tendencia

paises |>
  filter(CONTINENT == 'Africa' | CONTINENT == 'Europe') |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color = CONTINENT)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_y_continuous(labels = comma, limits = c(50, 90)) +
  ggtitle("PIB per cápita vs esperanza de vida al nacer por continente") +
  xlab("PIB per cápita  (USD)") +
  ylab("Esperanza de vida (años)") +
  labs(subtitle = "Datos de África y Europa", 
       caption = "Fuentes: Natural Earth y Banco Mundial",
       color = "Continente") +
  theme_bw() # tema de ggplot2
```

```{r}
#| label: grafico-13
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
# en África y Europa coloreado por continente
# + curva de tendencia


paises |>
  filter(CONTINENT == 'Africa' | CONTINENT == 'Europe') |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color = CONTINENT)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_y_continuous(labels = comma, limits = c(50, 90)) +
  ggtitle("PIB per cápita vs esperanza de vida al nacer por continente") +
  xlab("PIB per cápita  (USD)") +
  ylab("Esperanza de vida (años)") +
  labs(subtitle = "Datos de África y Europa", 
       caption = "Fuentes: Natural Earth y Banco Mundial",
       color = "Continente") +
  theme_ipsum() # tema de hrbrthemes
```

```{r}
#| label: grafico-14
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
#  coloreado por continente


paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color = CONTINENT)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_y_continuous(labels = comma, limits = c(50, 90)) +
  ggtitle("PIB per cápita vs esperanza de vida al nacer por continente") +
  xlab("PIB per cápita  (USD)") +
  ylab("Esperanza de vida (años)") +
  labs(caption = "Fuentes: Natural Earth y Banco Mundial",
       color = "Continente") +
  labs(color = "Población estimada") +
  scale_colour_brewer(palette = "YlOrBr", direction = -1) +
  theme_ipsum() # estilo de hrbrthemes
```


# Plotly

```{r}
#| label: grafico-15
#| warning: false
#| message: false

# Gráfico de dispersión de PIB per cápita vs esperanza de vida al nacer
grafico_ggplot2 <-
  paises |>
  ggplot(aes(x = GDP_PC, y = LIFE_EXPECTANCY, color = CONTINENT)) +
  geom_point(aes(
    # datos que se muestran al colocar el ratón sobre un punto
    text = paste0(
      "País: ", NAME, "\n",
      "PIB per cápita: ", GDP_PC, "\n",
      "Esperanza de vida: ", LIFE_EXPECTANCY
    )
  )) +
  scale_x_continuous(labels = comma, limits = c(0, NA)) +
  scale_y_continuous(labels = comma, limits = c(50, 90)) +
  ggtitle("PIB per cápita vs esperanza de vida al nacer por continente") +
  xlab("PIB per cápita  (USD)") +
  ylab("Esperanza de vida (años)") +
  labs(caption = "Fuentes: Natural Earth y Banco Mundial",
       color = "Continente") +
  labs(color = "Población estimada") +
  theme_ipsum() # estilo de hrbrthemes

# Gráfico plotly
ggplotly(grafico_ggplot2, tooltip = "text") |> 
  config(locale = 'es') # para mostrar los controles en español
```

